React events and state
Johnny-Baltazar/m3-0822-code-solutions pull request #13
Opened 2022-09-03 18:30 UTC by Johnny-Baltazar

![click-me-thank-you](https://user-images.githubusercontent.com/25161542/188283703-363b0b34-a980-4e03-af04-5d8d87df3ac2.gif)

2022-09-03 18:31 UTC, Johnny-Baltazar commented
Somehow my react-class-components exercise also got added with this one.

2022-09-07 03:09 UTC, scbowler requested changes
Looking good, but a couple updates needed. Let me know if you have any questions.

2022-09-07 03:09 UTC, scbowler commented on react-events-and-state/src/index.jsx
> +      this.props.text = 'Thank you!';
`this.props` is read only meaning we should never directly set any properties on it. Here it is better to use a variable:
```JSX
let text = '';

if (this.state.isClicked) {
  text = 'Thank you!';
} else {
  text = 'Click Me!';
}
```

2022-09-07 03:09 UTC, scbowler commented on react-events-and-state/src/index.jsx
> +          {this.props.text}
Here should use the `text` variable
```JSX
{ text }
```

2022-09-13 03:33 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2022-09-14 04:41 UTC, merged